# Generated by Django 3.0.6 on 2020-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200627_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_no', models.IntegerField()),
                ('p_address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('p_type', models.CharField(max_length=50)),
                ('t_weight', models.IntegerField()),
                ('p_decs', models.TextField(max_length=200)),
                ('p_time', models.TimeField()),
                ('p_n_time', models.TextField(max_length=2)),
                ('r_name', models.CharField(max_length=120)),
                ('r_contact_no', models.IntegerField()),
                ('d_address', models.CharField(max_length=200)),
                ('d_pincode', models.IntegerField()),
                ('date', models.DateField(default='12/12/2000')),
            ],
        ),
    ]
