# Generated by Django 3.0.6 on 2020-06-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200629_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courier_details',
            new_name='Courier_detail',
        ),
    ]
